# Generated by Django 3.2.7 on 2021-09-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discounts',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=20, verbose_name='Цена'),
        ),
    ]
