# Generated by Django 3.2.7 on 2021-09-23 07:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discount', '0002_alter_discounts_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=0, max_digits=20, verbose_name='Сумма заказа')),
                ('orderDate', models.DateTimeField(default=datetime.datetime(2021, 9, 23, 10, 59, 32, 678936), verbose_name='Время заказа')),
                ('deliveryDate', models.DateTimeField(default=datetime.datetime(2021, 9, 23, 10, 59, 32, 678936), verbose_name='Время доставки')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=150, verbose_name='Компания')),
                ('offer', models.TextField(verbose_name='Предложение')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discount.categories')),
            ],
            options={
                'verbose_name': 'Предложение',
                'verbose_name_plural': 'Предложения',
            },
        ),
    ]
