# Generated by Django 3.2.7 on 2021-09-23 08:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0004_auto_20210923_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='deliveryDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 23, 11, 6, 8, 213024), verbose_name='Время доставки'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='orderDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 23, 11, 6, 8, 213024), verbose_name='Время заказа'),
        ),
    ]
