# Generated by Django 3.2.7 on 2021-09-24 07:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0005_auto_20210923_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='deliveryDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 24, 10, 32, 41, 447075), verbose_name='Время доставки'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='orderDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 24, 10, 32, 41, 447075), verbose_name='Время заказа'),
        ),
    ]
