# Generated by Django 3.2.7 on 2021-10-01 09:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0006_auto_20210924_1032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Имя')),
                ('partner', models.TextField(verbose_name='Партнер')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.RemoveField(
            model_name='discounts',
            name='company',
        ),
        migrations.RemoveField(
            model_name='offers',
            name='company',
        ),
        migrations.AlterField(
            model_name='orders',
            name='deliveryDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 1, 12, 20, 43, 265462), verbose_name='Время доставки'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='orderDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 1, 12, 20, 43, 265462), verbose_name='Время заказа'),
        ),
        migrations.AddField(
            model_name='discounts',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='discount.companies'),
        ),
        migrations.AddField(
            model_name='offers',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='discount.companies'),
        ),
    ]
